baseurl = "/"
languageCode = "en-us"
title = "Visa Limbo"
theme = "flexible-seo-hugo"
googleAnalytics = ""
enableRobotsTXT = true
disableHugoGeneratorInject = true
pluralizelisttitles = false

[markup.goldmark.renderer]
unsafe = true

[Params]
  description = "A flexible SEO friendly theme for Hugo"
  schemas = []
  page_schemas = []
  seo = []
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/"
    weight = 10

[[menu.main]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/VisaLimbo"
  weight = -5
  

[taxonomies]


[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true

