baseurl = "/"
languageCode = "en-us"
title = "Visa Limbo"
theme = "flexible-seo-hugo"
googleAnalytics = ""
enableRobotsTXT = true
disableHugoGeneratorInject = true
pluralizelisttitles = false

[markup.goldmark.renderer]
unsafe = true

[Params]
  description = "A flexible SEO friendly theme for Hugo"
  schemas = []
  page_schemas = []
  seo = []
  body_classes = "avenir bg-near-white"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/VisaLimbo"

[taxonomies]


[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true

