baseurl = "/"
languageCode = "en-us"
title = "Visa Limbo"
theme = "flexible-seo-hugo"
googleAnalytics = ""
enableRobotsTXT = true
disableHugoGeneratorInject = true
pluralizelisttitles = false

[markup.goldmark.renderer]
unsafe = true

[Params]
  description = "A flexible SEO friendly theme for Hugo"
  schemas = []
  page_schemas = []
  seo = []

[[menu.main]]
  name = "Twitter"
  icon = "icon-twitter"
  url = "https://twitter.com/VisaLimbo"
  weight = -5

[[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "#"

[taxonomies]


[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true

